service: hello-sls
custom:
  webpack:
    config: ./webpack.config.js

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/rooms
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/rooms
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/messages.v2
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/messages.v2
    - Effect: Allow
      Action: dynamodb:Query
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/messages.v2/index/roomIdx
    - Effect: Allow
      Action: dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/connections
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/connections
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/connections
    - Effect: Allow
      Action: comprehend:DetectDominantLanguage
      Resource: "*"
    - Effect: Allow
      Action: translate:TranslateText
      Resource: "*"
    - Effect: Allow
      Action: execute-api:ManageConnections
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:${file(./.env.yml):wsApiGatewayId}/dev/POST/@connections/*
  environment:
    messages_table: messages.v2
    connections_table: connections
    rooms_table: rooms
  tags:
    Client: Animando
    Application: HelloSls

functions:
  websocket:
    handler: src/functions/websocket.handler
    layers:
      - ${file(./.env.yml):nodejsLayerArn}
  get-rooms:
    handler: src/functions/get-rooms.handler
    events:
      - http:
          path: /get-rooms
          method: GET
          cors: true
  create-room:
    handler: src/functions/create-room.handler
    events:
      - http:
          path: /create-room
          method: POST
          cors: true

resources:
  Resources:
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages.v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'roomIdx'
            KeySchema:
              - AttributeName: 'room'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL

    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'roomIdx'
            KeySchema:
              - AttributeName: 'room'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL

    roomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: room
            KeyType: HASH
package:
  exclude:
    - node_modules/**
    - '!node_modules/uuid/**'
