service: hello-sls
custom:
  webpack:
    config: ./webpack.config.js

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/messages.v2
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/messages.v2
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/connections
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/connections
    - Effect: Allow
      Action: comprehend:DetectDominantLanguage
      Resource: "*"
    - Effect: Allow
      Action: translate:TranslateText
      Resource: "*"
    - Effect: Allow
      Action: execute-api:ManageConnections
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:${file(./.env.yml):wsApiGatewayId}/dev/POST/@connections/*
  environment:
    messages_table: messages.v2
    connections_table: connections
  tags:
    Client: Animando
    Application: HelloSls

functions:
  # hello:
  #   handler: functions/hello.handler
  #   layers:
  #     - ${file(./.env.yml):nodejsLayerArn}
  #   events:
  #     - http:
  #         path: /
  #         method: GET
  # get-messages:
  #   handler: functions/get-messages.handler
  #   layers:
  #     - ${file(./.env.yml):nodejsLayerArn}
  #   events:
  #     - http:
  #         path: /get-messages
  #         method: GET
  #         cors: true
  # post-message:
  #   handler: functions/post-message.handler
  #   layers:
  #     - ${file(./.env.yml):nodejsLayerArn}
  #   events:
  #     - http:
  #         path: /post-message
  #         method: POST
  #         cors: true
  websocket:
    handler: functions/websocket.handler
    layers:
      - ${file(./.env.yml):nodejsLayerArn}

resources:
  Resources:
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages.v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH

    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'roomIdx'
            KeySchema:
              - AttributeName: 'room'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL
package:
  exclude:
    - node_modules/**
    - '!node_modules/uuid/**'
