service: hello-sls
custom:
  webpack:
    config: ./webpack.config.js
  tables:
    messages: ${env:MESSAGES_TABLE, 'messages.v2'}
    connections: ${env:CONNECTIONS_TABLE, 'connections'}
    rooms: ${env:ROOMS_TABLE, 'rooms'}
  config:
    dynamo_db_endpoint: ${env:DYNAMO_DB_ENDPOINT, ''}
    ws_api_gateway_id: ${env:WS_API_GATEWAY_ID}

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
    - Effect: Allow
      Action: dynamodb:Query
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}/index/roomIdx
    - Effect: Allow
      Action: dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
    - Effect: Allow
      Action: dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
    - Effect: Allow
      Action: dynamodb:Query
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}/index/roomIdx
    - Effect: Allow
      Action: comprehend:DetectDominantLanguage
      Resource: "*"
    - Effect: Allow
      Action: translate:TranslateText
      Resource: "*"
    - Effect: Allow
      Action: execute-api:ManageConnections
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:${self:custom.config.ws_api_gateway_id}/dev/POST/@connections/*
  environment:
    MESSAGES_TABLE: ${self:custom.tables.messages}
    CONNECTIONS_TABLE: ${self:custom.tables.connections}
    ROOMS_TABLE: ${self:custom.tables.rooms}
    DYNAMO_DB_ENDPOINT: ${self:custom.config.dynamo_db_endpoint}
  tags:
    Client: Animando
    Application: ChatServer

functions:
  websocket:
    handler: src/functions/websocket.handler
    layers:
      - ${env:NODE_JS_LAYER_ARN}
  get-rooms:
    handler: src/functions/get-rooms.handler
    events:
      - http:
          path: /get-rooms
          method: GET
          cors: true
  create-room:
    handler: src/functions/create-room.handler
    events:
      - http:
          path: /create-room
          method: POST
          cors: true

resources:
  Resources:
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages.v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'roomIdx'
            KeySchema:
              - AttributeName: 'room'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL

    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'roomIdx'
            KeySchema:
              - AttributeName: 'room'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL

    roomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.rooms}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: room
            AttributeType: S
        KeySchema:
          - AttributeName: room
            KeyType: HASH
package:
  exclude:
    - node_modules/**
    - '!node_modules/uuid/**'
