connectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tables.connections}
    Tags:
      - Key: Client
        Value: Animando
      - Key: Application
        Value: ChatServer
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      - AttributeName: room
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: 'roomIdx'
        KeySchema:
          - AttributeName: 'room'
            KeyType: 'HASH'
        Projection:
          ProjectionType: ALL
