connectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: connections
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      - AttributeName: room
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: 'roomIdx'
        KeySchema:
          - AttributeName: 'room'
            KeyType: 'HASH'
        Projection:
          ProjectionType: ALL
