- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
- Effect: Allow
  Action: dynamodb:Query
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}/index/roomIdx
- Effect: Allow
  Action: dynamodb:DeleteItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:Query
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}/index/roomIdx
- Effect: Allow
  Action: comprehend:DetectDominantLanguage
  Resource: "*"
- Effect: Allow
  Action: translate:TranslateText
  Resource: "*"
- Effect: Allow
  Action: execute-api:ManageConnections
  Resource:
    'Fn::Sub':
      - arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:#{chatapi}/${opt:stage}/POST/@connections/*
      - chatapi: {'Ref': 'ChatWebsocketApi'}
- Effect: Allow
  Action: execute-api:ManageConnections
  Resource:
    'Fn::Sub':
      - arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:#{loggerapi}/${opt:stage}/POST/@connections/*
      - loggerapi: {'Ref': 'LoggerWebsocketApi'}
