- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.rooms}
- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}
- Effect: Allow
  Action: dynamodb:Query
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.messages}/index/roomIdx
- Effect: Allow
  Action: dynamodb:DeleteItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:Scan
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:PutItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}
- Effect: Allow
  Action: dynamodb:Query
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tables.connections}/index/roomIdx
- Effect: Allow
  Action: comprehend:DetectDominantLanguage
  Resource: "*"
- Effect: Allow
  Action: translate:TranslateText
  Resource: "*"
- Effect: Allow
  Action: execute-api:ManageConnections
  Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:${self:custom.config.ws_api_gateway_id}/dev/POST/@connections/*
- Effect: Allow
  Action: execute-api:ManageConnections
  Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:${self:custom.config.ws_logger_api_gateway_id}/dev/POST/@connections/*
- Effect: Allow
  Action: execute-api:ManageConnections
  Resource:
    'Fn::Sub':
      - arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:#{apigateway}/${opt:stage}/POST/@connections/*
      - apigateway: {'Ref': 'ChatWebsocketApi'}
