roomsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tables.rooms}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: room
        AttributeType: S
    KeySchema:
      - AttributeName: room
        KeyType: HASH
